# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 11:01
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.create_id, max_length=200, primary_key=True, serialize=False),
        ),
    ]
