# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to=products.models.upload_product_file_loc),
        ),
    ]
